name: DDTV_Dev_CLI

on:
  push:
    tags:
      - "dev*"
  pull_request:
    branches-ignore: 
      - master 
    paths:
      - 'CLI/**'
      - '.github/workflows/DDTV_Dev_CLI.yml'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: linux-arm
          - os: windows-latest
            runtime: win-x64
          - os: macOS-latest
            runtime: osx-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: cd CLI && dotnet restore
  
      - name: Build
        run: cd CLI && dotnet publish --runtime ${{ matrix.runtime }} --configuration Release --self-contained true --output build_output/${{ matrix.runtime }}
  
      - name: Copy ffmpeg.exe (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir CLI\\build_output\\${{ matrix.runtime }}\\plugins\\ffmpeg
          copy CLI\\plugins\\ffmpeg\\ffmpeg.exe CLI\\build_output\\${{ matrix.runtime }}\\plugins\\ffmpeg\\ffmpeg.exe
          dir CLI\\build_output\\${{ matrix.runtime }}\\plugins\\ffmpeg
  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DDTV-CLI-${{ matrix.os }}-${{ matrix.runtime }}
          path: CLI/build_output/
