name: DDTV_Dev_CLI

on:
  push:
    tags:
      - "dev*"
  pull_request:
    branches-ignore: 
      - master 
    paths:
      - 'CLI/**'
      - '.github/workflows/DDTV_Dev_CLI.yml'
      - '!**/README.md'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        runtime: 
          - linux-x64
          - win-x64
          - osx-x64
          - linux-arm
          - win-arm
          - osx-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: cd CLI && dotnet restore
  
      - name: Build
        run: cd CLI && dotnet build --no-restore --output build_output --runtime ${{ matrix.runtime }} --self-contained true
  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DDTV-CLI-${{ matrix.os }}
          path: CLI/build_output
